[shell]
program = "fish"

[window]
padding = { x = 8, y = 8 }
opacity = 0.8
blur = true

[font]
normal = { family = "SauceCodePro NFM" }
size = 10.0

[colors.primary]
background = "0x222436"
foreground = "0xc8d3f5"

# Source: https://github.com/craftzdog/solarized-osaka.nvim/blob/main/extras/alacritty/solarized-osaka_moon.yml

[colors.normal]
black = "0x1b1d2b"
red = "0xff757f"
green = "0xc3e88d"
yellow = "0xffc777"
blue = "0x82aaff"
magenta = "0xc099ff"
cyan = "0x86e1fc"
white = "0x828bb8"

[colors.bright]
black = "0x444a73"
red = "0xff757f"
green = "0xc3e88d"
yellow = "0xffc777"
blue = "0x82aaff"
magenta = "0xc099ff"
cyan = "0x86e1fc"
white = "0xc8d3f5"

[[colors.indexed_colors]]
index = 16
color = "0xff966c"

[[colors.indexed_colors]]
index = 17
color = "0xc53b53"
